/**
 * 학습실 편집 콘텐츠. 한국어 소개·질문·정의·예시는 학습실 작성이며 원문 번역이 아니다.
 * 원문 제목과 도구 용도는 출처 목록을 확인했다. 파일 내부·발행일은 미확인이다.
 * 네트워크 요청이나 개인 기록 초기화 없이 DB seed 및 화면에서 사용할 수 있다.
 */
export interface ResourceSeed {
  id: string; titleKo: string; titleEn: string; summaryKo: string;
  kind: 'article' | 'catalog' | 'blog' | 'tool';
  format: 'html' | 'pdf' | 'xls' | 'xlsx';
  level: '입문' | '기초' | '중급' | '심화';
  priority: '필수' | '보충' | '심화' | '참조';
  url: string; author: string; tags: string[]; objectives: string[]; question: string;
}
export interface ModuleSeed {
  id: string; slug: string; order: number; titleKo: string; question: string;
  objectives: string[]; prerequisiteTermIds: string[]; resourceIds: string[]; questions: string[];
}
export interface GlossarySeed {
  id: string; termEn: string; termKo: string; acronym?: string; aliases: string[];
  definitionKo: string; formula?: string; exampleKo?: string; notes?: string;
  sources: string[]; moduleIds: string[]; revision: 1;
}
export interface ToolGuideSeed {
  resourceId: string; slug: string; purpose: string; inputs: string[]; steps: string[];
  interpretation: string; commonMistakes: string[]; sources: string[]; internalVerified: false;
}

const home = 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/';
const pc = 'https://pages.stern.nyu.edu/~adamodar/pc/';
const blog = 'https://aswathdamodaran.blogspot.com/';
const author = 'Aswath Damodaran';
const r = (data: Omit<ResourceSeed, 'author' | 'format'> & { format?: ResourceSeed['format'] }): ResourceSeed => ({ author, format: 'html', ...data });

export const resources: ResourceSeed[] = [
  r({ id:'R01', titleKo:'재무제표 입문', titleEn:'A Primer on Financial Statements', summaryKo:'이익·자산·부채를 읽고, 회계 숫자가 말해 주는 것과 놓치는 것을 살펴본다.', kind:'article', level:'입문', priority:'필수', url:home+'AccPrimer/accstate.htm', tags:['재무제표','회계','현금흐름'], objectives:['손익계산서·재무상태표·현금흐름표의 역할 구분','회계이익과 현금흐름의 차이 설명','장부가치와 평가가치의 차이 이해'], question:'이익이 나는데도 현금이 부족할 수 있을까?' }),
  r({ id:'R02', titleKo:'현재가치 입문', titleEn:'A Primer on the Time Value of Money', summaryKo:'서로 다른 시점의 돈을 같은 기준으로 비교하는 할인과 복리를 익힌다.', kind:'article', level:'입문', priority:'필수', url:home+'PVPrimer/pvprimer.htm', tags:['현재가치','복리','NPV'], objectives:['현금흐름을 시간선에 표시','현재가치와 미래가치 계산','연금과 영구연금의 조건 구분'], question:'1년 뒤 받을 돈을 오늘의 돈으로 어떻게 바꿀까?' }),
  r({ id:'R03', titleKo:'통계 입문', titleEn:'A Primer on Statistics', summaryKo:'평균·분산·상관·회귀를 읽으며 위험 측정의 언어를 준비한다.', kind:'article', level:'기초', priority:'보충', url:home+'StatFile/statistics.htm', tags:['통계','분산','회귀'], objectives:['평균과 분산의 역할 구분','상관계수와 회귀계수 해석','추정치의 오차를 인식'], question:'수익률의 평균만 알면 위험도 알 수 있을까?' }),
  r({ id:'R04', titleKo:'위험회피 입문', titleEn:'Risk Aversion', summaryKo:'불확실한 결과를 대하는 태도와 위험 보상이 필요한 이유를 생각한다.', kind:'article', level:'기초', priority:'보충', url:home+'risk/riskaversion.htm', tags:['위험','위험회피','기대효용'], objectives:['기대값과 확실한 금액의 차이 이해','위험회피와 위험프리미엄 연결'], question:'기대금액이 같아도 선택이 달라지는 이유는 무엇일까?' }),
  r({ id:'R05', titleKo:'가치평가 입문', titleEn:'An Introduction to Valuation', summaryKo:'가치평가의 역할과 주요 접근법을 살펴보고 학습의 지도를 만든다.', kind:'article', level:'입문', priority:'필수', url:home+'background/valintro.htm', tags:['가치평가','내재가치','가격'], objectives:['가치평가의 목적과 한계 이해','DCF와 상대가치평가의 근거 비교','가정과 편향을 기록하는 습관 만들기'], question:'정교한 계산이 곧 정확한 가치평가를 뜻할까?' }),
  r({ id:'R06', titleKo:'금융기초 슬라이드·확인문제', titleEn:'Corporate Finance Online Class', summaryKo:'금융기초 과정의 슬라이드와 확인문제·해답을 찾는 목록이다.', kind:'catalog', level:'입문', priority:'필수', url:home+'webcastfoundationsonline.htm', tags:['금융기초','슬라이드','확인문제'], objectives:['시간가치 기초를 슬라이드로 복습','개념 확인문제와 원문 해답 찾기'], question:'현재가치 계산의 조건을 문제에 적용할 수 있을까?' }),
  r({ id:'R07', titleKo:'회계 슬라이드·확인문제', titleEn:'Corporate Finance Online Class', summaryKo:'재무제표 학습을 보완할 슬라이드와 확인문제를 찾는다.', kind:'catalog', level:'입문', priority:'보충', url:home+'webcastacctg.htm', tags:['회계','슬라이드','확인문제'], objectives:['재무제표 항목을 복습','회계 이해를 확인하는 문제 찾기'], question:'각 재무제표에서 필요한 숫자를 찾을 수 있을까?' }),
  r({ id:'R08', titleKo:'기업재무 강의노트', titleEn:'Corporate Finance Lecture Notes', summaryKo:'투자·자금조달·배당 의사결정의 강의노트를 찾는다. Packet 1·2부터 읽는다.', kind:'catalog', level:'기초', priority:'필수', url:home+'cflect.htm', tags:['기업재무','투자','자본구조'], objectives:['위험에 맞는 요구수익률 이해','투자안과 조달 구조의 연결 파악','배당 의사결정의 기준 정리'], question:'기업이 돈을 투자하고 빌리고 돌려줄 때 어떤 기준이 필요할까?' }),
  r({ id:'R09', titleKo:'기업재무 문제·해답', titleEn:'Corporate Finance Problem Sets', summaryKo:'기업재무 개념을 계산과 판단으로 점검하는 원문 문제 목록이다.', kind:'catalog', level:'기초', priority:'필수', url:home+'cfprset.htm', tags:['기업재무','문제','해답'], objectives:['현금흐름과 할인율을 문제에 적용','풀이 후 원문 해답과 비교'], question:'문제의 숫자를 계산하기 전에 가정을 설명할 수 있을까?' }),
  r({ id:'R10', titleKo:'기업재무 보충 읽을거리', titleEn:'Corporate Finance Readings', summaryKo:'투자·조달·배당을 더 생각해 볼 질문과 글을 주제별로 찾는다.', kind:'catalog', level:'중급', priority:'보충', url:home+'cfread.htm', tags:['기업재무','보충','의사결정'], objectives:['기업재무 원칙을 사례와 연결','추가 설명이 필요한 주제 선택'], question:'교재의 원칙은 실제 기업의 선택을 어떻게 설명할까?' }),
  r({ id:'R11', titleKo:'가치평가 강의노트', titleEn:'Valuation Lecture Notes', summaryKo:'Introduction, Part I DCF, Part II 상대가치평가를 중심으로 읽는 강의노트 목록이다.', kind:'catalog', level:'중급', priority:'필수', url:home+'eqlect.htm', tags:['DCF','상대가치평가','강의노트'], objectives:['현금흐름·성장·할인율의 연결 이해','DCF와 배수 접근 비교','주주가치까지의 조정 과정 파악'], question:'가치평가의 각 입력값은 서로 어떻게 연결될까?' }),
  r({ id:'R12', titleKo:'DCF 문제·해답', titleEn:'Discounted Cashflow Valuation Problems and Solutions', summaryKo:'할인율·현금흐름·성장 가정을 원문 문제로 점검한다.', kind:'article', level:'중급', priority:'필수', url:home+'problems/dcfprob.htm', tags:['DCF','문제','해답'], objectives:['현금흐름에 맞는 할인율 선택','입력 가정의 일관성 확인','원문 풀이와 자신의 근거 비교'], question:'현금흐름과 할인율을 바꾸면 평가가치가 왜 달라질까?' }),
  r({ id:'R13', titleKo:'상대가치 문제·해답', titleEn:'Relative Valuation Problems and Solutions', summaryKo:'비교기업과 배수를 선택할 때 숨어 있는 가정을 확인한다.', kind:'article', level:'중급', priority:'필수', url:home+'problems/relval.htm', tags:['상대가치평가','배수','문제'], objectives:['배수의 분자·분모 일치 확인','비교기업의 차이 설명','원문 문제와 해답 비교'], question:'산업 평균 배수를 그대로 쓰면 어떤 가정을 하게 될까?' }),
  r({ id:'R14', titleKo:'DCF 25문 25답', titleEn:'25 DCF valuation questions', summaryKo:'DCF를 만들며 자주 부딪히는 질문을 주제별로 찾아 읽는다.', kind:'article', level:'중급', priority:'필수', url:home+'valquestions/valquestions.htm', tags:['DCF','질문','복습'], objectives:['DCF 가정의 논리 점검','모호한 입력의 판단 근거 정리'], question:'내 DCF에서 가장 자신 없는 가정은 무엇일까?' }),
  r({ id:'R15', titleKo:'가치평가 보충 읽을거리', titleEn:'Readings for Valuation', summaryKo:'가치평가 주제별 설명과 사례를 더 읽는 목록이다.', kind:'catalog', level:'중급', priority:'보충', url:home+'eqread.htm', tags:['가치평가','사례','보충'], objectives:['관심 주제의 보충 근거 찾기','사례와 일반 원칙 구분'], question:'내 평가 가정을 보완할 자료는 어디에 있을까?' }),
  r({ id:'R16', titleKo:'금융지표·비율 정의', titleEn:'Financial Ratios and Measures', summaryKo:'지표의 계산 범위와 해석상 주의점을 확인하는 참조 자료다.', kind:'article', level:'기초', priority:'참조', url:home+'definitions.html', tags:['비율','정의','용어'], objectives:['비율의 분자와 분모 확인','동일 명칭의 계산 차이 파악'], question:'같은 ROIC라도 계산자가 다르면 값이 달라질까?' }),
  r({ id:'R17', titleKo:'기본 금융용어사전', titleEn:'Glossary', summaryKo:'영문 금융용어를 확인할 수 있는 원문 사전이다.', kind:'article', level:'입문', priority:'참조', url:home+'glossary.htm', tags:['사전','영문','기초'], objectives:['낯선 금융용어의 원문 의미 확인','문맥에 맞는 용어 해석'], question:'이 용어가 지금 문장에서는 어떤 의미로 쓰였을까?' }),
  r({ id:'R18', titleKo:'Excel 도구 목록', titleEn:'Spreadsheet programs', summaryKo:'분석 목적에 맞는 원본 Excel을 찾고 도구의 범위를 확인한다.', kind:'catalog', level:'기초', priority:'참조', url:home+'spreadsh.htm', tags:['Excel','실습','도구'], objectives:['분석 목적과 모델 연결','도구에 필요한 개념 확인'], question:'내가 풀려는 문제에 맞는 계산 도구는 무엇일까?' }),
  r({ id:'R19', titleKo:'논문·심화 글 목록', titleEn:'Research and Papers', summaryKo:'기초 경로를 마친 뒤 특정 주제를 깊이 읽는 참조 목록이다.', kind:'catalog', level:'심화', priority:'심화', url:home+'papers.html', tags:['논문','심화','연구'], objectives:['심화 학습할 주제 선택','원문 논증의 근거 추적'], question:'기초 모형으로 설명하기 어려운 부분은 무엇일까?' }),
  r({ id:'R20', titleKo:'현재 데이터 안내', titleEn:'Useful Data Sets', summaryKo:'실습 입력의 원천을 찾는 안내다. 각 파일의 실제 기준일을 따로 확인한다.', kind:'catalog', level:'중급', priority:'보충', url:home+'data.html', tags:['데이터','기준일','실습'], objectives:['입력 데이터의 출처 확인','자료의 기준일·통화·집계 범위 확인'], question:'분석에 쓴 데이터는 언제, 어떤 범위로 만들어졌을까?' }),
  r({ id:'B01', titleKo:'내재가치의 의미', titleEn:'Thoughts on intrinsic value', summaryKo:'가치 추정의 의미와 추정치가 달라질 수 있는 이유를 생각한다. 과거 시점의 글이다.', kind:'blog', level:'기초', priority:'보충', url:blog+'2011/06/thoughts-on-intrinsic-value.html', tags:['내재가치','관점'], objectives:['가치 추정과 관측 가격 구분','추정의 불확실성 인식'], question:'내재가치는 누구에게나 같은 하나의 숫자일까?' }),
  r({ id:'B02', titleKo:'숫자와 내러티브', titleEn:'Numbers and Narrative: Modeling, Story Telling and Investing', summaryKo:'사업에 관한 이야기를 매출·마진·투자 가정으로 연결해 본다. 과거 사례를 사용한다.', kind:'blog', level:'기초', priority:'보충', url:blog+'2014/06/numbers-and-narrative-modeling-story.html', tags:['내러티브','가정','사업'], objectives:['사업 이야기를 수치 가정으로 표현','이야기와 계산의 모순 점검'], question:'이 기업의 성장 이야기는 어떤 숫자로 드러나야 할까?' }),
  r({ id:'B03', titleKo:'DCF에 대한 오해들', titleEn:'Discounted Cashflow Valuations (DCF): Academic Exercise, Sales Pitch or Investor Tool?', summaryKo:'DCF를 사용하는 목적과 흔한 오해를 읽는다. 당시 논의를 오늘의 투자 결론과 구분한다.', kind:'blog', level:'기초', priority:'보충', url:blog+'2015/02/discounted-cashflow-valuations-dcf.html', tags:['DCF','관점','가정'], objectives:['DCF 활용 목적 정리','정밀한 계산과 신뢰할 만한 가정 구분'], question:'DCF는 어떤 질문에 답할 때 유용할까?' }),
  r({ id:'B04', titleKo:'DCF의 일관성', titleEn:'DCF Myth 1: If you have a D(discount rate) and a CF (cash flow), you have a DCF!', summaryKo:'계산 전에 현금흐름과 할인율의 대상·통화·기준이 맞는지 점검한다.', kind:'blog', level:'중급', priority:'필수', url:blog+'2015/02/dcf-myth-1-if-you-have-ddiscount-rate.html', tags:['DCF','일관성','할인율'], objectives:['FCFF와 FCFE의 할인율 구분','명목·실질·통화 기준 일치 확인'], question:'숫자를 할인하기만 하면 올바른 DCF가 될까?' }),
  r({ id:'B05', titleKo:'성장의 한계', titleEn:'Growth (Part 1): The Limits of Growth', summaryKo:'고성장이 얼마나 오래 이어질 수 있는지 생각한다. 기업 수치는 당시 사례다.', kind:'blog', level:'중급', priority:'보충', url:blog+'2011/10/growth-part-1-limits-of-growth.html', tags:['성장','계속가치','시장규모'], objectives:['고성장 기간의 근거 점검','시장 규모와 성장 가정 연결'], question:'지금의 높은 성장률을 얼마나 오래 유지할 수 있을까?' }),
  r({ id:'B06', titleKo:'성장의 가치', titleEn:'Growth (Part 3): The Value of Growth', summaryKo:'성장에 필요한 투자와 그 수익률을 함께 보며 가치 창출을 판단한다.', kind:'blog', level:'중급', priority:'필수', url:blog+'2011/10/growth-part-3-value-of-growth.html', tags:['성장','재투자','ROIC'], objectives:['성장과 가치 창출을 구분','재투자 수익률과 자본비용 비교'], question:'매출과 이익이 늘어도 기업가치가 줄어들 수 있을까?' }),
  r({ id:'T01', titleKo:'수익률 계산기', titleEn:'Return Calculator', summaryKo:'장부상 투자금 대비 ROE·ROIC를 계산하며 이익의 질을 살펴본다.', kind:'tool', format:'xls', level:'기초', priority:'필수', url:pc+'returncalculator.xls', tags:['Excel','ROE','ROIC'], objectives:['자기자본과 투하자본 수익률 구분','이익과 자본의 측정 범위 일치'], question:'기존 사업은 투입한 자본에 비해 얼마나 벌었을까?' }),
  r({ id:'T02', titleKo:'투자안 분석', titleEn:'Capital Budgeting', summaryKo:'프로젝트의 현금흐름과 NPV·IRR을 비교하는 실습 도구다.', kind:'tool', format:'xls', level:'기초', priority:'필수', url:pc+'capbudg.xls', tags:['Excel','NPV','IRR'], objectives:['투자안 현금흐름 구성','NPV와 IRR의 해석 비교'], question:'이 프로젝트가 요구수익률을 넘어 가치를 만들까?' }),
  r({ id:'T03', titleKo:'내재 주식위험프리미엄', titleEn:'Implied ERP', summaryKo:'시장가격과 미래 지급액 가정에서 요구수익률을 역산해 본다.', kind:'tool', format:'xls', level:'중급', priority:'보충', url:pc+'implprem.xls', tags:['Excel','ERP','위험'], objectives:['내재 ERP와 과거 ERP 구분','가격과 성장 가정의 영향 확인'], question:'시장가격에는 어느 정도의 위험 보상이 반영되어 있을까?' }),
  r({ id:'T04', titleKo:'차입과 무차입 베타', titleEn:'Lever/Unlever Beta', summaryKo:'차입비율에 따라 주식의 베타가 어떻게 달라지는지 살펴본다.', kind:'tool', format:'xls', level:'기초', priority:'필수', url:pc+'levbeta.xls', tags:['Excel','베타','자본구조'], objectives:['사업위험과 재무위험 구분','차입비율 변화의 베타 영향 확인'], question:'같은 사업이라도 빚이 늘면 주주의 위험은 어떻게 변할까?' }),
  r({ id:'T05', titleKo:'합성 신용등급', titleEn:'Synthetic Rating', summaryKo:'이자보상배율을 이용해 등급과 부채비용을 추정하는 원리를 익힌다.', kind:'tool', format:'xls', level:'중급', priority:'보충', url:pc+'ratings.xls', tags:['Excel','신용등급','부채비용'], objectives:['이자보상배율과 부도위험 연결','추정 등급의 한계 이해'], question:'공식 신용등급이 없으면 부채비용을 어떻게 가늠할까?' }),
  r({ id:'T06', titleKo:'WACC 계산기', titleEn:'WACC Calculator', summaryKo:'자기자본과 부채의 비용을 같은 기준의 가중치로 결합한다.', kind:'tool', format:'xls', level:'기초', priority:'필수', url:pc+'wacccalc.xls', tags:['Excel','WACC','할인율'], objectives:['자금 원천별 비용 구분','시장가치 가중치와 세후 부채비용 적용'], question:'기업 전체의 현금흐름에는 어떤 할인율이 맞을까?' }),
  r({ id:'T07', titleKo:'안정성장기 투자 추정', titleEn:'Capex Estimator', summaryKo:'안정성장기의 순자본적 지출 가정을 점검한다.', kind:'tool', format:'xls', level:'중급', priority:'보충', url:pc+'cpxest.xls', tags:['Excel','재투자','안정성장'], objectives:['총투자와 순투자 구분','성장과 재투자 가정의 연결 확인'], question:'안정적으로 성장하려면 얼마를 다시 투자해야 할까?' }),
  r({ id:'T08', titleKo:'계속가치에 내재된 수익률', titleEn:'Implied ROC/ROE', summaryKo:'계속가치의 성장·재투자 가정이 암묵적으로 요구하는 수익률을 확인한다.', kind:'tool', format:'xls', level:'중급', priority:'보충', url:pc+'ImpliedROCROE.xls', tags:['Excel','계속가치','ROIC'], objectives:['계속가치의 내재 수익률 점검','성장과 재투자 비율의 일관성 검토'], question:'내 계속가치 가정은 얼마나 높은 투자수익률을 요구할까?' }),
  r({ id:'T09', titleKo:'기업 DCF 실습', titleEn:'Simple FCFF Ginzu', summaryKo:'일반 비금융기업의 매출·마진·재투자를 연결해 DCF를 만들어 본다.', kind:'tool', format:'xlsx', level:'중급', priority:'필수', url:pc+'fcffsimpleginzu.xlsx', tags:['Excel','DCF','FCFF'], objectives:['사업 가정을 현금흐름으로 연결','기업가치에서 주주가치로 조정','입력 가정과 결과를 함께 설명'], question:'이 기업의 가치 추정을 한 장의 이야기로 설명할 수 있을까?' }),
  r({ id:'T10', titleKo:'기업가치 배수 실습', titleEn:'Firm Multiples', summaryKo:'성장·위험·수익성 가정과 기업가치 배수의 관계를 비교한다.', kind:'tool', format:'xls', level:'중급', priority:'필수', url:pc+'firmmult.xls', tags:['Excel','상대가치평가','배수'], objectives:['기초 가정에서 배수의 차이 설명','DCF와 기업가치 배수 연결'], question:'높은 배수는 어떤 성장·수익성 가정을 필요로 할까?' }),
];

export const modules: ModuleSeed[] = [
  { id:'M01', slug:'financial-statements', order:1, titleKo:'재무제표 읽기', question:'이익과 현금은 왜 다른가?', objectives:['세 재무제표가 연결되는 방식 이해','매출·영업이익·순이익을 구분','장부가치와 현금흐름의 차이를 설명'], prerequisiteTermIds:['G22','G23','G24','G37'], resourceIds:['R01','R07','T01','R16'], questions:['외상매출이 발생하면 이익과 현금은 어떻게 달라질까?','공장을 구입한 지출과 감가상각비는 왜 따로 보는가?','자사주 매입 뒤 ROE가 높아지면 수익성이 개선되었다고 말할 수 있을까?'] },
  { id:'M02', slug:'time-value-of-money', order:2, titleKo:'돈의 시간가치', question:'미래의 돈을 오늘 얼마로 볼까?', objectives:['현금흐름을 시간선 위에 배치','복리와 할인의 역관계 이해','연금·영구연금·NPV 계산 조건 점검'], prerequisiteTermIds:['G01','G02','G03','G04'], resourceIds:['R02','R06','R09','T02'], questions:['같은 금액을 더 늦게 받으면 현재가치는 어떻게 달라질까?','연간 할인율을 월별 현금흐름에 그대로 쓰면 무엇이 잘못될까?','NPV가 양수라는 말은 어떤 기준에 비해 이익이라는 뜻인가?'] },
  { id:'M03', slug:'risk-and-return', order:3, titleKo:'위험과 요구수익률', question:'위험에 맞는 수익률은 무엇인가?', objectives:['전체 위험과 시장위험 구분','베타와 ERP의 역할 이해','사업위험과 차입의 효과 분리'], prerequisiteTermIds:['G03','G09','G10','G11','G41','G42'], resourceIds:['R03','R04','R08','T03','T04','T05'], questions:['변동성이 큰 주식은 반드시 베타도 높을까?','과거 회귀베타가 미래 사업을 잘 대표하지 못하는 경우는 언제인가?','부채가 늘 때 자기자본비용도 그대로 두어도 될까?'] },
  { id:'M04', slug:'corporate-finance', order:4, titleKo:'기업의 재무 의사결정', question:'좋은 투자와 적절한 차입은 무엇인가?', objectives:['투자수익률을 적절한 자본비용과 비교','NPV와 현금흐름을 연결','투자·차입·배당의 관계 이해'], prerequisiteTermIds:['G07','G08','G14','G15','G17','G20','G21'], resourceIds:['R08','R09','R10','T01','T02','T06'], questions:['ROIC와 자기자본비용을 바로 비교해도 될까?','부채비용이 자기자본비용보다 낮으면 빚을 무한히 늘려도 좋을까?','투자 기회와 현금 여력이 배당 결정에 어떻게 영향을 줄까?'] },
  { id:'M05', slug:'valuation-map', order:5, titleKo:'가치평가의 지도', question:'가치와 가격은 어떻게 다른가?', objectives:['내재가치와 시장가격 구분','기업 전체와 주주의 청구권 구분','이야기를 검토 가능한 가정으로 바꾸기'], prerequisiteTermIds:['G01','G03','G33','G34','G35','G36'], resourceIds:['R05','R11','B01','B02','B03','B04'], questions:['주가를 알고 있어도 가치평가를 하는 이유는 무엇인가?','영업자산가치에서 주주가치로 이동할 때 무엇을 더하고 빼야 할까?','성장 이야기와 마진 가정이 서로 모순되는 사례를 생각해 보자.'] },
  { id:'M06', slug:'discounted-cash-flow', order:6, titleKo:'DCF 만들기', question:'미래 현금흐름을 어떻게 추정할까?', objectives:['매출·마진·재투자를 FCFF로 연결','현금흐름과 할인율의 일관성 확인','계속가치와 안정성장 가정 점검'], prerequisiteTermIds:['G17','G21','G25','G27','G28','G29','G31','G32'], resourceIds:['R11','R12','R14','T06','T07','T08','T09','B05','B06'], questions:['매출이 늘어날 때 재투자를 늘리지 않아도 되는 조건은 무엇인가?','FCFF를 자기자본비용으로 할인하면 대상이 왜 어긋나는가?','계속가치 계산에 마지막 예측연도와 그 다음 해 중 어느 현금흐름을 쓰는가?','성장률만 높이면 가치가 반드시 늘어날까?'] },
  { id:'M07', slug:'relative-valuation', order:7, titleKo:'상대가치평가', question:'비교기업의 배수를 언제 믿을까?', objectives:['주식 배수와 기업 배수의 대상을 구분','기간·회계·통화 기준을 맞추어 비교','성장·위험·수익성 차이를 배수로 설명'], prerequisiteTermIds:['G20','G21','G34','G35','G38','G39','G40','G43'], resourceIds:['R11','R13','R15','T10'], questions:['시가총액을 EBITDA로 나누면 어떤 권리의 범위가 어긋날까?','같은 업종의 두 기업에 서로 다른 PER가 정당화되는 이유는 무엇인가?','순이익이 음수인 기업을 PER 평균에서 어떻게 다룰까?'] },
  { id:'M08', slug:'review-and-practice', order:8, titleKo:'종합 복습', question:'내 가정과 계산을 설명할 수 있을까?', objectives:['DCF 실습의 입력 출처와 기준일 기록','계산 결과를 배수 관점과 비교','추정의 한계와 다음 확인 사항 정리'], prerequisiteTermIds:['G07','G17','G29','G31','G34','G35','G40'], resourceIds:['R12','R13','R14','R15','T09','T10'], questions:['가치에 가장 큰 영향을 주는 가정 세 가지는 무엇인가?','DCF 결과와 비교기업 배수가 다르면 어떤 입력부터 점검할까?','다른 사람이 같은 출처로 내 계산을 재현할 수 있는가?'] },
];

const pv = home+'PVPrimer/pvprimer.htm';
const accounting = home+'AccPrimer/accstate.htm';
const definitions = home+'definitions.html';
const glossarySource = home+'glossary.htm';
const investment = home+'AppldCF/derivn/ch5deriv.html';
const terminal = home+'AppldCF/derivn/ch12deriv.html';
const fcff = home+'lectures/fcff.html';
const fcfe = home+'lectures/fcfe.html';
const relative = home+'problems/relval.htm';
const stats = home+'StatFile/statistics.htm';
const g = (data: Omit<GlossarySeed, 'revision' | 'aliases'> & { aliases?: string[] }): GlossarySeed => ({ revision:1, aliases:[], ...data, notes:'학습실 작성 정의·예시. '+(data.notes ?? '원문의 계산 범위와 가정을 함께 확인한다.') });

export const glossary: GlossarySeed[] = [
  g({id:'G01',termEn:'Present Value',termKo:'현재가치',acronym:'PV',definitionKo:'미래의 현금흐름을 위험과 시점에 맞는 할인율로 오늘 시점에 환산한 금액이다.',formula:'PV = CFₜ / (1 + r)ᵗ',exampleKo:'1년 뒤 110원을 받고 할인율이 10%라면 현재가치는 100원이다.',sources:[pv],moduleIds:['M02','M05']}),
  g({id:'G02',termEn:'Future Value',termKo:'미래가치',acronym:'FV',definitionKo:'현재 금액에 기간별 수익률을 적용해 미래 시점으로 옮긴 금액이다.',formula:'FV = PV × (1 + r)ⁿ',exampleKo:'100원이 연 10%로 2년간 복리로 늘면 121원이다.',sources:[pv],moduleIds:['M02']}),
  g({id:'G03',termEn:'Discount Rate',termKo:'할인율',definitionKo:'미래 현금흐름의 현재가치를 구할 때 사용하는 기간별 요구수익률이다.',notes:'현금흐름의 통화·명목/실질·세후 기준과 위험에 맞춰 선택한다.',sources:[blog+'2015/02/dcf-myth-1-if-you-have-ddiscount-rate.html'],moduleIds:['M02','M03','M06']}),
  g({id:'G04',termEn:'Compounding',termKo:'복리 계산',aliases:['복리'],definitionKo:'원금뿐 아니라 앞선 기간에 붙은 수익에도 다음 기간의 수익률을 적용하는 계산이다.',formula:'기말 금액 = 원금 × (1 + 기간 수익률)ⁿ',notes:'연·월 등 수익률과 기간 단위를 맞춘다.',sources:[pv],moduleIds:['M02']}),
  g({id:'G05',termEn:'Annuity',termKo:'연금',definitionKo:'일정한 간격으로 같은 금액이 정해진 횟수만큼 발생하는 현금흐름이다.',formula:'기말 지급 연금 PV = A × [1 − (1 + r)⁻ⁿ] / r',notes:'공식은 첫 지급이 한 기간 뒤이고 r ≠ 0일 때다. 기초 지급은 시점을 조정한다.',sources:[pv],moduleIds:['M02']}),
  g({id:'G06',termEn:'Perpetuity',termKo:'영구연금',definitionKo:'같은 금액이 일정한 간격으로 끝없이 발생한다고 가정한 현금흐름이다.',formula:'PV = A / r',notes:'첫 지급은 한 기간 뒤, 일정한 r > 0을 가정한다. 성장 영구연금은 CF₁/(r−g)이며 r > g가 필요하다.',sources:[pv],moduleIds:['M02','M06']}),
  g({id:'G07',termEn:'Net Present Value',termKo:'순현재가치',acronym:'NPV',definitionKo:'초기 투자와 이후 현금 유입·유출을 같은 시점으로 할인해 모두 더한 순가치다.',formula:'NPV = Σ CFₜ / (1 + r)ᵗ, t = 0…n',exampleKo:'오늘 100원을 투자하고 1년 뒤 121원을 받으며 할인율이 10%이면 NPV는 10원이다.',sources:[investment],moduleIds:['M02','M04']}),
  g({id:'G08',termEn:'Internal Rate of Return',termKo:'내부수익률',acronym:'IRR',definitionKo:'투자안의 순현재가치를 0으로 만드는 할인율이다.',formula:'0 = Σ CFₜ / (1 + IRR)ᵗ',notes:'현금흐름의 부호가 여러 번 바뀌면 해가 여러 개이거나 없을 수 있다. 규모·시점이 다른 투자안은 NPV도 함께 비교한다.',sources:[investment],moduleIds:['M02','M04']}),
  g({id:'G09',termEn:'Risk-free Rate',termKo:'무위험수익률',aliases:['무위험이자율','무위험금리'],definitionKo:'평가에 쓰는 통화와 기간에서 지급 불확실성을 제거한 기준 수익률이다.',notes:'모든 국채금리가 항상 무위험인 것은 아니다. 현금흐름과 통화·만기를 맞추고 신용위험 여부를 확인한다.',sources:[glossarySource],moduleIds:['M03','M06']}),
  g({id:'G10',termEn:'Equity Risk Premium',termKo:'주식위험프리미엄',acronym:'ERP',aliases:['주식 위험 프리미엄'],definitionKo:'주식시장 위험을 부담하는 대가로 무위험수익률보다 추가로 요구하는 기대수익률이다.',formula:'ERP = E(Rₘ) − Rf',notes:'과거 평균으로 측정한 값과 현재 가격에서 역산한 내재 프리미엄은 산출 방법이 다르다.',sources:[glossarySource],moduleIds:['M03','M06']}),
  g({id:'G11',termEn:'Beta',termKo:'베타',aliases:['β','시장 베타'],definitionKo:'자산 수익률이 시장 수익률과 함께 움직이는 민감도다. 전체 변동성과는 다르다.',formula:'β = Cov(Rᵢ, Rₘ) / Var(Rₘ)',notes:'회귀 기간·빈도·시장지수에 따라 추정치가 달라진다.',sources:[definitions,stats],moduleIds:['M03']}),
  g({id:'G12',termEn:'Unlevered Beta',termKo:'무차입 베타',aliases:['언레버드 베타'],definitionKo:'자기자본 베타에서 차입의 영향을 분리해 사업위험을 가늠한 베타다.',formula:'βᵤ = βₗ / [1 + (1 − t)D/E]',notes:'대표적인 단순식은 부채베타를 0으로 보고 일정한 세금효과를 가정한다. 현금 조정 여부도 확인한다.',sources:[definitions],moduleIds:['M03']}),
  g({id:'G13',termEn:'Bottom-up Beta',termKo:'상향식 베타',aliases:['바텀업 베타'],definitionKo:'비슷한 사업을 하는 기업들의 베타를 바탕으로 사업별 위험을 추정하고 대상 기업의 사업 구성과 차입을 반영한 베타다.',notes:'비교기업의 차입·현금 효과를 먼저 정리하고 대상 기업의 가중치를 적용한다.',sources:[definitions],moduleIds:['M03','M06']}),
  g({id:'G14',termEn:'Cost of Equity',termKo:'자기자본비용',aliases:['주주 요구수익률'],definitionKo:'주주가 해당 기업의 위험을 부담하는 대가로 요구하는 기대수익률이다.',formula:'CAPM 예: Ke = Rf + β × ERP',notes:'회사가 현금으로 지급하는 수수료가 아니다. 예시 공식의 위험 모형과 추가 위험 조정 여부를 확인한다.',sources:[glossarySource],moduleIds:['M03','M04','M06']}),
  g({id:'G15',termEn:'Cost of Debt',termKo:'부채비용',definitionKo:'현재 위험과 시장 조건에서 기업이 차입할 때 부담할 한계 조달비용이다.',formula:'세전 Kd ≈ Rf + 부도위험 스프레드',notes:'과거 발행 채권의 표면금리와 구분한다. 이자 세금효과를 적용할 때 공제 가능성을 확인한다.',sources:[glossarySource],moduleIds:['M03','M04','M06']}),
  g({id:'G16',termEn:'Cost of Capital',termKo:'자본비용',definitionKo:'기업에 자본을 제공하는 투자자들이 요구하는 수익률을 자금 원천별로 종합한 비용이다.',notes:'DCF의 일반 비금융기업 분석에서는 보통 WACC를 뜻한다. 자기자본비용과 같은 뜻으로 쓰지 않는다.',sources:[fcff],moduleIds:['M04','M06']}),
  g({id:'G17',termEn:'Weighted Average Cost of Capital',termKo:'가중평균자본비용',acronym:'WACC',definitionKo:'자기자본비용과 세후 부채비용을 시장가치 비중으로 평균한 기업 전체의 요구수익률이다.',formula:'WACC = Ke × E/(D+E) + Kd × (1−t) × D/(D+E)',notes:'보통주와 부채만 있는 단순식이다. 우선주 등 다른 자금 원천은 별도로 반영한다.',sources:[fcff],moduleIds:['M04','M06']}),
  g({id:'G18',termEn:'Default Spread',termKo:'부도위험 스프레드',aliases:['신용 스프레드'],definitionKo:'채무불이행 위험이 있는 채권의 요구수익률이 같은 통화·유사 만기의 무위험 기준보다 높은 부분이다.',formula:'스프레드 ≈ 위험 채권 수익률 − 무위험 기준 수익률',notes:'관측 스프레드에는 유동성 등 다른 요인도 포함될 수 있다.',sources:[glossarySource],moduleIds:['M03']}),
  g({id:'G19',termEn:'Interest Coverage Ratio',termKo:'이자보상배율',aliases:['이자보상비율'],definitionKo:'영업이익으로 이자비용을 얼마나 감당할 수 있는지 나타내는 배율이다.',formula:'이자보상배율 = EBIT / 이자비용',notes:'합성등급은 추정치이며 공식 신용평가가 아니다. 일회성 이익과 적자를 점검한다.',sources:[accounting],moduleIds:['M03','M04']}),
  g({id:'G20',termEn:'Return on Equity',termKo:'자기자본이익률',acronym:'ROE',definitionKo:'보통주 주주에게 귀속되는 순이익을 장부상 자기자본과 비교한 회계 수익률이다.',formula:'ROE = 보통주 귀속 순이익 / 장부상 자기자본',notes:'기초 또는 평균 자본 중 어느 기준인지 명시한다. 자기자본이 작거나 음수이면 해석이 왜곡된다.',sources:[accounting],moduleIds:['M01','M04','M07']}),
  g({id:'G21',termEn:'Return on Invested Capital',termKo:'투하자본수익률',acronym:'ROIC',definitionKo:'영업에 투입한 자본에 비해 세후 영업이익을 얼마나 벌었는지 나타내는 수익률이다.',formula:'ROIC = 조정 EBIT × (1−t) / 영업 투하자본',notes:'이익과 자본의 조정 범위를 맞춘다. 기초/평균 자본, 현금·영업권 처리에 따라 값이 달라진다.',sources:[investment],moduleIds:['M01','M04','M06','M07']}),
  g({id:'G22',termEn:'Revenue',termKo:'매출액',aliases:['매출','Sales'],definitionKo:'재화나 서비스를 제공해 벌어들인 금액으로, 해당 기간의 인식 기준에 따라 기록한다.',notes:'대금을 실제로 받은 시점과 매출을 인식한 시점은 다를 수 있다.',sources:[accounting],moduleIds:['M01','M06']}),
  g({id:'G23',termEn:'Operating Income',termKo:'영업이익',acronym:'EBIT',aliases:['이자 및 세전 이익'],definitionKo:'영업 활동의 수익에서 영업 비용을 차감한 이익이다. 분석에서는 이자·세전 영업성과를 출발점으로 삼는다.',notes:'재무제표상 영업이익과 EBIT·조정 EBIT는 항상 같지 않다. 비영업 항목과 조정 내역을 확인한다.',sources:[accounting],moduleIds:['M01','M06']}),
  g({id:'G24',termEn:'Net Income',termKo:'순이익',aliases:['당기순이익'],definitionKo:'수익에서 해당 기간의 비용과 세금 등을 반영하고 남은 회계상 이익이다.',notes:'전체 연결 순이익과 보통주 주주 귀속 순이익을 구분하며, 현금흐름으로 바로 취급하지 않는다.',sources:[accounting],moduleIds:['M01','M07']}),
  g({id:'G25',termEn:'Capital Expenditure',termKo:'자본적 지출',acronym:'Capex',aliases:['설비투자'],definitionKo:'여러 기간에 걸쳐 효익을 낼 자산을 취득하거나 개선하는 지출이다.',notes:'가치평가에서는 회계상 설비투자 외에 연구개발·인수 등 성장 투자 조정을 검토할 수 있다.',sources:[investment],moduleIds:['M01','M06']}),
  g({id:'G26',termEn:'Depreciation and Amortization',termKo:'감가상각·무형자산상각',acronym:'D&A',aliases:['감가상각','상각비'],definitionKo:'장기간 사용하는 유형·무형자산의 원가를 여러 기간의 비용으로 배분하는 회계 처리다.',notes:'당기 상각비 자체가 당기의 현금 지급은 아니다. 현금흐름 계산에서 투자 지출과 따로 반영한다.',sources:[investment],moduleIds:['M01','M06']}),
  g({id:'G27',termEn:'Working Capital',termKo:'운전자본',aliases:['운전자금'],definitionKo:'사업 운영에 묶인 단기 자금이다. 통상 순운전자본은 유동자산에서 유동부채를 뺀다.',formula:'분석용 비현금 운전자본 = 비현금 유동자산 − 비이자성 유동부채',notes:'순운전자본과 비현금 운전자본은 계산 범위가 달라 단순한 동의어가 아니다. 분석용 정의는 현금과 이자부 부채를 보통 제외하며 증가는 대체로 현금 유출이다.',sources:[definitions,investment],moduleIds:['M01','M06']}),
  g({id:'G28',termEn:'Reinvestment Rate',termKo:'재투자율',definitionKo:'세후 영업이익 가운데 순투자와 운전자본 증가에 사용하는 비중이다.',formula:'재투자율 = (Capex − D&A + Δ비현금 운전자본) / EBIT(1−t)',notes:'성장률 ≈ 재투자율 × 신규 투자수익률의 연결을 점검한다. 이익이 0·음수면 비율 해석에 주의한다.',sources:[blog+'2011/10/growth-part-3-value-of-growth.html'],moduleIds:['M06']}),
  g({id:'G29',termEn:'Free Cash Flow to Firm',termKo:'기업잉여현금흐름',acronym:'FCFF',definitionKo:'영업세금과 재투자를 반영한 뒤 부채·자기자본 제공자 전체에 귀속될 수 있는 현금흐름이다.',formula:'FCFF = EBIT(1−t) + D&A − Capex − Δ비현금 운전자본',notes:'차입과 이자 지급 전 기준이며 일반적으로 WACC로 할인한다.',sources:[fcff],moduleIds:['M06','M08']}),
  g({id:'G30',termEn:'Free Cash Flow to Equity',termKo:'주주잉여현금흐름',acronym:'FCFE',definitionKo:'영업·재투자와 순차입을 반영한 뒤 주주에게 귀속될 수 있는 현금흐름이다.',formula:'FCFE = 순이익 + D&A − Capex − Δ비현금 운전자본 + 신규차입 − 원금상환',notes:'배당과 반드시 같지는 않다. 자기자본비용으로 할인하며 차입 정책의 가정을 확인한다.',sources:[fcfe],moduleIds:['M06']}),
  g({id:'G31',termEn:'Terminal Value',termKo:'계속가치',aliases:['터미널 가치'],definitionKo:'명시적 예측기간 이후의 현금흐름을 예측기간 말 시점에서 평가한 가치다.',formula:'TVₙ = FCFFₙ₊₁ / (WACC − g)',notes:'안정성장 FCFF 예시이며 WACC > g가 필요하다. 오늘의 가치로 다시 할인한다. 프로젝트 청산 잔존가치와 구분한다.',sources:[terminal],moduleIds:['M06','M08']}),
  g({id:'G32',termEn:'Stable Growth',termKo:'안정성장',definitionKo:'장기에 지속 가능한 수준으로 성장·위험·수익성·재투자 가정이 정착한 상태다.',notes:'단지 낮은 성장률 하나를 넣는 것이 아니다. 통화·인플레이션·경제 규모 및 성장에 필요한 재투자를 함께 고려한다.',sources:[terminal,blog+'2011/10/growth-part-1-limits-of-growth.html'],moduleIds:['M06']}),
  g({id:'G33',termEn:'Intrinsic Value',termKo:'내재가치',definitionKo:'자산의 현금 창출력·성장·위험 등 경제적 기초에 관한 가정에서 추정한 가치다.',notes:'시장가격과 다를 수 있으며 확정된 정답이 아니다. 입력 근거와 불확실성을 함께 설명한다.',sources:[blog+'2011/06/thoughts-on-intrinsic-value.html'],moduleIds:['M05']}),
  g({id:'G34',termEn:'Enterprise Value',termKo:'기업가치',acronym:'EV',aliases:['엔터프라이즈 가치'],definitionKo:'통상 영업자산에 대한 자본 제공자 전체의 가치를 뜻한다. 주식만의 가치와 구분한다.',formula:'통상 EV = 시가총액 + 부채 + 우선주 + 비지배지분 − 현금·비영업 금융자산',notes:'EV와 firm value가 문맥에 따라 다른 범위를 가리킬 수 있다. 부채·리스·현금 등의 포함 범위를 명시한다.',sources:[relative],moduleIds:['M05','M07','M08']}),
  g({id:'G35',termEn:'Equity Value',termKo:'주주가치',aliases:['자기자본가치','지분가치'],definitionKo:'부채 등 다른 청구권을 고려한 뒤 주주에게 귀속되는 지분의 가치다.',notes:'DCF 추정 주주가치와 시장에서 관측한 시가총액을 구분한다. 주당가치 계산은 희석 가능 청구권도 점검한다.',sources:[fcfe,home+'background/valintro.htm'],moduleIds:['M05','M08']}),
  g({id:'G36',termEn:'Market Capitalization',termKo:'시가총액',aliases:['시총'],definitionKo:'시장 주가에 해당 주식 수를 곱한 관측 가능한 주식의 시장가치다.',formula:'시가총액 = 주가 × 유통 중인 주식 수',notes:'주식 종류·자기주식 제외 여부·기준일을 확인한다. 부채를 포함한 기업가치와 다르다.',sources:[glossarySource],moduleIds:['M05','M07']}),
  g({id:'G37',termEn:'Book Value',termKo:'장부가치',aliases:['장부금액'],definitionKo:'회계기준에 따라 자산·부채·자본에 기록한 금액이다.',notes:'시장가격이나 내재가치와 같다고 가정하지 않는다. PBR의 장부가치는 보통 보통주 자기자본을 뜻한다.',sources:[accounting],moduleIds:['M01','M07']}),
  g({id:'G38',termEn:'Price/Earnings Ratio',termKo:'주가수익비율',acronym:'PER',aliases:['P/E','PE','이익배수'],definitionKo:'주가를 주당순이익으로 나눈 주식 가격의 이익 대비 배수다.',formula:'PER = 주가 / EPS = 시가총액 / 대응 순이익',notes:'과거/예상 이익, 일회성 항목, 보통주 귀속 범위를 맞춘다. 적자일 때 일반적인 배수 비교가 어렵다.',sources:[relative],moduleIds:['M07']}),
  g({id:'G39',termEn:'Price/Book Ratio',termKo:'주가순자산비율',acronym:'PBR',aliases:['P/B','PB','장부가치배수'],definitionKo:'주식 시장가치를 대응하는 장부상 자기자본과 비교한 배수다.',formula:'PBR = 시가총액 / 보통주 장부상 자기자본',notes:'낮은 PBR만으로 저평가라고 판단하지 않는다. ROE·위험·성장과 장부가치의 측정 한계를 함께 본다.',sources:[relative],moduleIds:['M07']}),
  g({id:'G40',termEn:'EV/EBITDA',termKo:'기업가치/EBITDA 배수',aliases:['EV EBITDA'],definitionKo:'기업가치를 이자·세금·감가상각·무형자산상각 차감 전 이익과 비교한 배수다.',formula:'EV/EBITDA = EV / EBITDA',notes:'EBITDA는 재투자와 운전자본을 차감하지 않아 현금흐름과 다르다. 리스 처리와 회계 범위를 기업 간 맞춘다.',sources:[relative],moduleIds:['M07','M08']}),
  g({id:'G41',termEn:'Variance',termKo:'분산',definitionKo:'관측값이 평균에서 얼마나 퍼져 있는지를 편차의 제곱으로 나타낸 척도다.',formula:'표본분산 s² = Σ(xᵢ − x̄)² / (n − 1)',notes:'수익률 전체의 변동성을 나타내며 시장위험만 측정하는 베타와 다르다.',sources:[stats],moduleIds:['M03']}),
  g({id:'G42',termEn:'Correlation',termKo:'상관계수',aliases:['상관관계'],definitionKo:'두 변수 사이의 선형 동행 정도를 −1부터 +1 사이로 표준화한 수치다.',formula:'ρ(X,Y) = Cov(X,Y) / (σX × σY)',notes:'상관은 인과관계를 증명하지 않는다. 0인 상관도 비선형 관계가 없다는 뜻은 아니다.',sources:[stats],moduleIds:['M03']}),
  g({id:'G43',termEn:'EBITDA',termKo:'이자·세금·상각 전 이익',acronym:'EBITDA',definitionKo:'EBIT에 감가상각·무형자산상각을 다시 더해 살펴보는 이익 지표다.',formula:'EBITDA = EBIT + D&A',notes:'회사가 발표하는 조정 EBITDA는 제외 항목이 추가될 수 있다. 현금흐름이나 배당 가능액으로 간주하지 않는다.',sources:[home+'problems/relval.htm'],moduleIds:['M01','M07']}),
  g({id:'G44',termEn:'Regression',termKo:'회귀분석',aliases:['회귀'],definitionKo:'설명변수와 결과변수의 관계를 자료에서 추정하는 통계 방법이다.',formula:'단순 선형 회귀: Y = a + bX + ε',notes:'기울기는 다른 조건과 추정 범위 안에서 읽는다. 표준오차·관측기간·모형 가정을 함께 확인한다.',sources:[stats],moduleIds:['M03']}),
];

export const toolGuides: ToolGuideSeed[] = [
  {resourceId:'T01',slug:'return-calculator',purpose:'ROE와 ROIC를 계산하며 이익의 대상과 투입 자본의 범위를 맞추는 실습이다.',inputs:['분석 기간의 순이익과 영업이익','같은 기준의 장부상 자기자본·이자부 부채·현금','세율 및 일회성 항목의 조정 근거'],steps:['원본 사본을 열어 파일의 입력 설명과 기준 기간을 확인한다.','순이익은 자기자본에, 세후 영업이익은 영업 투하자본에 대응시킨다.','기초 또는 평균 자본 중 사용한 기준과 조정 항목을 메모한다.','ROE와 ROIC를 각각 자기자본비용과 자본비용에 비교한다.'],interpretation:'수익률은 기존 자본의 회계상 성과다. 분모 축소만으로 비율이 높아질 수 있으므로 이익과 자본 변화를 함께 본다.',commonMistakes:['장부가치 대신 시가총액을 ROE 분모로 사용','현금을 차감한 자본과 현금 이익을 포함한 이익을 혼합','음수 자기자본의 ROE를 정상 기업과 비교'],sources:[home+'spreadsh.htm',accounting,investment],internalVerified:false},
  {resourceId:'T02',slug:'capital-budgeting',purpose:'투자안의 증분 현금흐름으로 NPV·IRR을 비교하는 실습이다.',inputs:['초기 투자금과 투자 기간','기간별 증분 매출·비용·세금','설비투자·상각·운전자본 및 종료 회수액','현금흐름과 일치하는 할인율'],steps:['투자하지 않는 경우와 비교해 추가되는 현금흐름을 정리한다.','초기 투자와 각 기간의 유입·유출 시점을 구분한다.','동일 통화·기간·세후 기준으로 가정을 맞춘다.','NPV와 IRR을 함께 읽고 매출·비용 가정을 하나씩 바꾸어 비교한다.'],interpretation:'NPV는 선택한 요구수익률을 반영한 순가치다. IRR은 비율이므로 규모가 다른 투자안의 가치 창출액을 대신하지 못한다.',commonMistakes:['이미 지출한 매몰비용을 신규 투자비에 포함','회계이익을 현금흐름으로 그대로 사용','운전자본 투입·회수를 누락','NPV와 IRR의 순위가 다를 때 이유를 무시'],sources:[home+'spreadsh.htm',investment,pv],internalVerified:false},
  {resourceId:'T03',slug:'implied-erp',purpose:'시장가격을 설명하는 주식 요구수익률을 역산하는 개념을 익힌다.',inputs:['같은 기준일의 시장지수 수준','지수의 배당·자사주 매입 등 지급액 가정','예측 성장과 안정성장 가정','지급액과 같은 통화의 무위험수익률'],steps:['파일이 요구하는 지급액 범위와 기준 시점을 확인한다.','가격과 지급액·성장 전망의 출처를 함께 기록한다.','계산된 시장 요구수익률과 무위험수익률의 차이를 해석한다.','가격 또는 성장 가정을 바꾸어 내재 프리미엄의 변화를 비교한다.'],interpretation:'내재 ERP는 가격과 미래 가정을 만족시키는 추정치다. 과거 초과수익률 평균과 같은 측정값이 아니며 입력이 바뀌면 함께 바뀐다.',commonMistakes:['다른 날짜의 가격·지급액·금리 혼합','배당과 자사주 매입 범위 불일치','실현수익률 보장값으로 해석'],sources:[home+'spreadsh.htm',glossarySource,home+'problems/dcfprob.htm'],internalVerified:false},
  {resourceId:'T04',slug:'lever-unlever-beta',purpose:'사업위험을 유지한 채 차입비율 변화가 주주 위험에 주는 영향을 비교한다.',inputs:['현재 자기자본 베타','적용 세율','동일 시점의 부채/자기자본 시장가치 비율','비교할 차입비율'],steps:['베타의 출처와 추정 기간을 확인한다.','현재 차입의 효과를 분리해 무차입 베타를 구한다.','비교할 차입비율을 적용한 베타 변화를 읽는다.','세율·부채 위험·현금 조정 가정을 메모한다.'],interpretation:'차입이 커지면 같은 영업 변동도 주주에게 더 크게 전달될 수 있다. 결과는 선택한 베타 조정 모형의 가정에 따른 값이다.',commonMistakes:['D/E와 D/(D+E)를 혼동','장부가치와 시장가치 비율을 혼합','차입을 바꾸면서 사업위험까지 바뀌는 상황을 무시'],sources:[home+'spreadsh.htm',definitions],internalVerified:false},
  {resourceId:'T05',slug:'synthetic-rating',purpose:'이자 지급 능력에서 합성등급과 부채비용을 추정하는 흐름을 익힌다.',inputs:['대표성이 있는 영업이익','같은 기간의 이자비용','무위험수익률','파일의 등급·스프레드 표가 적용되는 기업 구분과 기준일'],steps:['일회성 항목이 영업이익을 왜곡하는지 확인한다.','이자보상배율을 계산하고 파일의 분류 기준을 읽는다.','합성등급에 연결된 스프레드와 그 기준일을 확인한다.','추정 부채비용이 실제 조달 조건과 얼마나 다른지 근거를 남긴다.'],interpretation:'합성등급은 간략한 재무지표에 근거한 추정이다. 실제 신용등급이나 대출 제안이 아니며 스프레드는 시점에 따라 달라진다.',commonMistakes:['낡은 스프레드를 현재 값으로 간주','이자비용 0 또는 적자 상황을 정상 구간처럼 처리','일회성 이익으로 상환 능력을 과대평가'],sources:[home+'spreadsh.htm',accounting,glossarySource],internalVerified:false},
  {resourceId:'T06',slug:'wacc-calculator',purpose:'기업 전체 현금흐름에 대응하는 가중평균자본비용을 계산한다.',inputs:['무위험수익률·ERP·베타 등 자기자본비용의 근거','현재 세전 부채비용과 적용 세율','부채·자기자본의 시장가치 또는 목표 비중','분석 통화와 기준일'],steps:['자기자본비용과 부채비용을 같은 통화·시점 기준으로 정리한다.','적용 가능한 이자 세금효과를 확인한다.','시장가치 비중으로 비용을 결합한다.','자본구조가 달라질 때 자금 원천별 위험도 함께 점검한다.'],interpretation:'WACC는 FCFF의 위험과 대응시켜 사용하는 요구수익률이다. 회사의 과거 평균 조달금리나 모든 프로젝트에 공통으로 쓰는 금리가 아니다.',commonMistakes:['FCFE를 WACC로 할인','현재 조달비용 대신 과거 표면금리만 사용','세금효과를 두 번 차감','부채비중만 바꾸고 위험을 고정'],sources:[home+'spreadsh.htm',fcff,blog+'2015/02/dcf-myth-1-if-you-have-ddiscount-rate.html'],internalVerified:false},
  {resourceId:'T07',slug:'capex-estimator',purpose:'안정성장기의 순자본적 지출 가정을 성장과 자본 효율에 비추어 검토한다.',inputs:['안정성장률의 근거','안정기 영업이익과 투자수익률 가정','자본적 지출·감가상각의 범위','기존 자본과 운전자본 투자 가정'],steps:['총자본적 지출과 감가상각 차감 후 순투자를 구분한다.','파일이 제시하는 추정 접근법의 입력과 가정을 읽는다.','성장에 필요한 재투자와 추정 순투자가 양립하는지 비교한다.','운전자본을 포함한 전체 재투자도 따로 점검한다.'],interpretation:'안정기 투자액은 과거 평균을 그대로 연장하는 값이 아니다. 성장·수익률·감가상각·운전자본 가정과 함께 설명해야 한다.',commonMistakes:['양의 성장을 가정하면서 재투자를 무조건 0으로 설정','총투자와 순투자를 혼동','설비투자만 보고 다른 성장 투자를 누락'],sources:[home+'spreadsh.htm',investment,blog+'2011/10/growth-part-3-value-of-growth.html'],internalVerified:false},
  {resourceId:'T08',slug:'implied-returns',purpose:'계속가치 계산의 성장·재투자 가정에 내재된 ROC 또는 ROE가 합리적인지 점검한다.',inputs:['안정기 성장률','재투자율 또는 유보율','기업 기준인지 주주 기준인지의 구분','비교할 자본비용과 사업의 수익성 근거'],steps:['계속가치를 계산한 현금흐름의 대상을 먼저 확인한다.','안정기 성장과 재투자·유보 가정을 정리한다.','내재된 ROC·ROE를 관련 요구수익률 및 사업 여건과 비교한다.','과도한 수익률이 나오면 성장과 재투자 가정을 함께 다시 검토한다.'],interpretation:'성장이 같은데 재투자를 줄이면 모형이 요구하는 투자수익률은 높아진다. 결과는 가정의 진단이며 실제 미래 성과의 예측 보장이 아니다.',commonMistakes:['기업 재투자율과 주주 유보율을 혼합','분모가 0에 가까운 비율을 정상 추정치로 취급','과거 평균 수익률이 영구히 지속된다고 가정'],sources:[home+'spreadsh.htm',terminal,blog+'2011/10/growth-part-3-value-of-growth.html'],internalVerified:false},
  {resourceId:'T09',slug:'fcff-simple-ginzu',purpose:'일반 비금융기업의 사업 가정을 FCFF와 주주가치로 이어 보는 종합 실습이다.',inputs:['최근 매출·영업이익·세금과 기준 통화','성장률·목표 마진·재투자 효율 가정','할인율과 안정성장 가정','부채·현금·비영업자산 및 주식 관련 청구권 정보'],steps:['원본의 설명과 기본 가정을 읽고 자신의 분석 범위를 정한다.','기업 공시에서 입력을 모으고 각 숫자의 기준일·단위를 기록한다.','사업 이야기에 맞춰 성장·마진·재투자를 함께 조정한다.','영업자산가치에서 주주가치로 이어지는 조정 항목을 확인한다.','핵심 가정을 하나씩 바꾸어 결과 차이와 이유를 메모한다.'],interpretation:'출력은 입력한 가정을 현금가치로 환산한 추정이다. 기본값이 있다고 기업에 적합한 값은 아니며 은행 등 금융기업에는 별도 모형 검토가 필요하다.',commonMistakes:['원·백만원 또는 달러 단위를 혼합','높은 성장을 넣고 투자 필요액은 그대로 유지','현금이나 부채를 두 번 조정','원본 기본값을 조사한 기업의 사실로 간주'],sources:[home+'spreadsh.htm',fcff,home+'background/valintro.htm'],internalVerified:false},
  {resourceId:'T10',slug:'firm-multiples',purpose:'기업가치 배수를 성장·위험·재투자 등 기초 가정과 연결해 비교한다.',inputs:['기업 기준 현금흐름의 성장 가정','자본비용과 안정기 조건','수익성·재투자 관련 가정','비교 배수의 분자·분모와 계산 시점'],steps:['파일의 2단계 FCFF 접근과 필요한 가정을 확인한다.','배수의 이익 기준이 과거인지 예상인지 명시한다.','성장·자본비용·수익성을 하나씩 바꾸며 배수 변화를 비교한다.','실제 비교기업과 차이가 나는 이유를 같은 입력 기준으로 정리한다.'],interpretation:'이 도구는 기초 가정이 암시하는 기업가치 배수를 살펴본다. 시장의 산업 평균 배수를 자동으로 정답으로 만들지는 않는다.',commonMistakes:['기업가치 분자에 주주 순이익 분모를 대응','비교기업의 성장·위험·재투자 차이 무시','다른 기간이나 회계 기준의 배수를 직접 비교'],sources:[home+'spreadsh.htm',relative],internalVerified:false},
];
