import { z } from 'zod';
import { toolGuides } from '../content';
import { config } from './config';
import { db,id,now,json } from './db';
import { getTranslationForBlock } from './translation';
import { translationRuntime } from './translation/runtime';
import { translationGlossaryInfo } from './translation/glossary';
import { reviewedTranslationPairs } from './translation/memory';

export class AppError extends Error {constructor(public code:string,message:string,public status=400){super(message);}}
export type Row=Record<string,any>;
const parseList=(v:unknown)=>z.array(z.string()).parse(json(v,[]));
export function resourceRows(){
  return db().prepare(`SELECT r.*,COALESCE(p.priority_override,r.priority) as effective_priority,
    (SELECT COUNT(*) FROM source_versions v WHERE v.resource_id=r.id) as version_count,
    (SELECT id FROM source_versions v WHERE v.resource_id=r.id AND v.extraction_status IN ('ready','completed','partial','ocr_needed','not_applicable') ORDER BY imported_at DESC LIMIT 1) as version_id,
    EXISTS(SELECT 1 FROM bookmarks b WHERE b.resource_id=r.id AND b.source_version_id IS NULL) as bookmarked
    FROM resources r LEFT JOIN resource_preferences p ON p.resource_id=r.id ORDER BY r.id`).all().map(raw=>{
      const r=raw as Row;const counts=r.version_id?db().prepare(`SELECT COUNT(*) as total FROM source_blocks b WHERE source_version_id=? AND type<>'image' AND TRIM(text)<>''`).get(r.version_id) as Row:{total:0};
      const translatedCount=r.version_id?(db().prepare("SELECT DISTINCT b.id FROM source_blocks b JOIN translations t ON t.block_id=b.id WHERE b.source_version_id=? AND b.type<>'image' AND TRIM(b.text)<>'' AND (t.validation_status='passed' OR EXISTS(SELECT 1 FROM translation_review_links l WHERE l.translation_id=t.id))").all(r.version_id) as {id:string}[]).filter(b=>{const t=getTranslationForBlock(b.id);return t?.current&&t.validationStatus==='passed';}).length:0;
      return {id:r.id,titleKo:r.title_ko,titleEn:r.title_en,summaryKo:r.summary_ko,kind:r.kind,format:r.format,level:r.level,priority:r.effective_priority,url:r.canonical_url,author:r.author,tags:parseList(r.tags_json),objectives:parseList(r.objectives_json),question:r.question,sourceType:r.source_type,sourceStatus:r.source_status,versionId:r.version_id,versionCount:r.version_count,blockCount:counts.total,translatedCount,bookmarked:!!r.bookmarked,moduleIds:(db().prepare('SELECT module_id FROM module_resources WHERE resource_id=?').all(r.id) as Row[]).map(x=>x.module_id)};
    });
}
export function moduleRows(){return (db().prepare('SELECT * FROM modules ORDER BY sort_order').all() as Row[]).map(m=>({id:m.id,slug:m.slug,order:m.sort_order,titleKo:m.title_ko,question:m.question,objectives:parseList(m.objectives_json),questions:parseList(m.questions_json),resourceIds:(db().prepare('SELECT resource_id FROM module_resources WHERE module_id=? ORDER BY sort_order').all(m.id) as Row[]).map(x=>x.resource_id),prerequisiteTermIds:(db().prepare("SELECT term_id FROM module_terms WHERE module_id=? AND role='prerequisite' ORDER BY sort_order").all(m.id) as Row[]).map(x=>x.term_id)}));}
export function glossaryRows(){return (db().prepare('SELECT * FROM glossary_terms ORDER BY term_ko').all() as Row[]).map(g=>({id:g.id,termEn:g.term_en,termKo:g.term_ko,acronym:g.acronym,aliases:parseList(g.aliases_json),definitionKo:g.definition_ko,formula:g.formula,exampleKo:g.example_ko,notes:g.notes,sources:parseList(g.sources_json),revision:g.revision,moduleIds:(db().prepare('SELECT module_id FROM module_terms WHERE term_id=?').all(g.id) as Row[]).map(x=>x.module_id)}));}
export function versionRow(v:Row){return {id:v.id,resourceId:v.resource_id,fileHash:v.file_hash,format:v.format,pageCount:v.page_count,importedAt:v.imported_at,publishedAt:v.published_at,declaredVersion:v.declared_version,finalUrl:v.final_url,mime:v.mime,byteSize:v.byte_size,extractionStatus:v.extraction_status,warnings:parseList(v.warnings_json)};}
export function getVersion(resourceId:string,versionId:string){const v=db().prepare('SELECT * FROM source_versions WHERE id=? AND resource_id=?').get(versionId,resourceId) as Row|undefined;if(!v)throw new AppError('VERSION_NOT_FOUND','이 자료에 속하는 원문 버전을 찾을 수 없습니다.',404);return v;}
export function validateLocation(data:{resourceId:string;sourceVersionId?:string|null;blockId?:string|null;pageIndex?:number|null}){
  if(!db().prepare('SELECT id FROM resources WHERE id=?').get(data.resourceId))throw new AppError('NOT_FOUND','자료를 찾을 수 없습니다.',404);
  if((data.blockId||data.pageIndex!=null)&&!data.sourceVersionId)throw new AppError('VERSION_REQUIRED','문단·페이지를 저장하려면 원문 버전이 필요합니다.');
  if(data.sourceVersionId){const v=getVersion(data.resourceId,data.sourceVersionId);if(data.pageIndex!=null&&(v.format!=='pdf'||data.pageIndex<0||data.pageIndex>=v.page_count))throw new AppError('PAGE_INVALID','해당 원문에 없는 페이지입니다.');
    if(data.blockId){const b=db().prepare('SELECT * FROM source_blocks WHERE id=? AND source_version_id=?').get(data.blockId,v.id) as Row|undefined;if(!b)throw new AppError('BLOCK_INVALID','해당 버전에 없는 문단입니다.');if(data.pageIndex!=null&&b.page_index!==data.pageIndex)throw new AppError('PAGE_MISMATCH','문단과 페이지가 일치하지 않습니다.');}
  }
}
export const locationSchema=z.object({resourceId:z.string().min(1),sourceVersionId:z.string().min(1).nullish(),blockId:z.string().min(1).nullish(),pageIndex:z.number().int().nonnegative().nullish()});
const noteSchema=locationSchema.extend({quote:z.string().max(10000).nullish(),text:z.string().trim().min(1).max(20000)});
export function noteRows(){return (db().prepare('SELECT n.*,r.title_ko FROM notes n JOIN resources r ON r.id=n.resource_id ORDER BY updated_at DESC').all() as Row[]).map(n=>({id:n.id,resourceId:n.resource_id,sourceVersionId:n.source_version_id,blockId:n.block_id,pageIndex:n.page_index,quote:n.quote,text:n.text,updatedAt:n.updated_at,titleKo:n.title_ko}));}
export function saveNote(input:unknown,noteId?:string){const n=noteSchema.parse(input);validateLocation(n);if(noteId&&!db().prepare('SELECT id FROM notes WHERE id=?').get(noteId))throw new AppError('NOT_FOUND','메모가 없습니다.',404);const key=noteId||id();db().prepare(`INSERT INTO notes VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET text=excluded.text,quote=excluded.quote,updated_at=excluded.updated_at`).run(key,n.resourceId,n.sourceVersionId||null,n.blockId||null,n.pageIndex??null,n.quote||null,n.text,now());return noteRows().find(x=>x.id===key);}
export function bookmarkRows(){return (db().prepare('SELECT b.*,r.title_ko FROM bookmarks b JOIN resources r ON r.id=b.resource_id ORDER BY created_at DESC').all() as Row[]).map(b=>({id:b.id,resourceId:b.resource_id,sourceVersionId:b.source_version_id,blockId:b.block_id,pageIndex:b.page_index,createdAt:b.created_at,titleKo:b.title_ko}));}
export function saveBookmark(input:unknown){const b=locationSchema.parse(input);validateLocation(b);const location=JSON.stringify([b.resourceId,b.sourceVersionId||null,b.blockId||null,b.pageIndex??null]);const key=id();db().prepare('INSERT INTO bookmarks VALUES(?,?,?,?,?,?,?) ON CONFLICT(location_key) DO NOTHING').run(key,b.resourceId,b.sourceVersionId||null,b.blockId||null,b.pageIndex??null,location,now());return bookmarkRows().find(x=>x.id===(db().prepare('SELECT id FROM bookmarks WHERE location_key=?').get(location) as Row).id);}
export function positionRows(){return (db().prepare('SELECT p.*,r.title_ko FROM reading_positions p JOIN resources r ON r.id=p.resource_id ORDER BY updated_at DESC').all() as Row[]).map(p=>({resourceId:p.resource_id,sourceVersionId:p.source_version_id,blockId:p.block_id,pageIndex:p.page_index,offset:p.offset,languageMode:p.language_mode,updatedAt:p.updated_at,titleKo:p.title_ko}));}
export function savePosition(input:unknown){const p=locationSchema.extend({sourceVersionId:z.string().min(1),offset:z.number().min(0).max(10000000).default(0),languageMode:z.enum(['ko','en','parallel'])}).parse(input);validateLocation(p);db().prepare('INSERT INTO reading_positions VALUES(?,?,?,?,?,?,?) ON CONFLICT(resource_id,source_version_id) DO UPDATE SET block_id=excluded.block_id,page_index=excluded.page_index,offset=excluded.offset,language_mode=excluded.language_mode,updated_at=excluded.updated_at').run(p.resourceId,p.sourceVersionId,p.blockId||null,p.pageIndex??null,p.offset,p.languageMode,now());return {saved:true};}
export function progressRows(){return (db().prepare('SELECT * FROM learning_progress').all() as Row[]).map(p=>({moduleId:p.module_id,status:p.status,completedAt:p.completed_at,updatedAt:p.updated_at}));}
export function saveProgress(moduleId:string,input:unknown){const {status}=z.object({status:z.enum(['not_started','in_progress','completed'])}).parse(input);if(!db().prepare('SELECT id FROM modules WHERE id=?').get(moduleId))throw new AppError('NOT_FOUND','단원을 찾을 수 없습니다.',404);db().prepare('INSERT INTO learning_progress VALUES(?,?,?,?) ON CONFLICT(module_id) DO UPDATE SET status=excluded.status,completed_at=excluded.completed_at,updated_at=excluded.updated_at').run(moduleId,status,status==='completed'?now():null,now());return {moduleId,status};}
const settingSchema=z.object({fontSize:z.number().int().min(14).max(26).optional(),languageMode:z.enum(['ko','en','parallel']).optional()}).strict();
export function getSettings(){const values:Record<string,unknown>={fontSize:17,languageMode:'parallel'};for(const s of db().prepare('SELECT * FROM settings').all() as Row[])if(s.key==='fontSize'||s.key==='languageMode')values[s.key]=json(s.non_secret_value_json,null);return settingSchema.required().parse(values);}
export function saveSettings(input:unknown){const parsed=settingSchema.parse(input);db().transaction(()=>{for(const [k,v]of Object.entries(parsed))db().prepare('INSERT INTO settings VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET non_secret_value_json=excluded.non_secret_value_json,updated_at=excluded.updated_at').run(k,JSON.stringify(v),now());})();return getSettings();}
export function translationStatus(){
  const runtime=translationRuntime();
  const record=db().prepare("SELECT non_secret_value_json FROM settings WHERE key='translationVerification'").get() as Row|undefined;
  const verified=z.object({provider:z.enum(['argos','finetuned','hymt','openai']).default('openai'),model:z.string(),promptVersion:z.string(),verifiedAt:z.string()}).safeParse(json(record?.non_secret_value_json,null));
  return {provider:runtime.provider,providerLabel:runtime.providerLabel,local:runtime.local,apiKeyRequired:runtime.apiKeyRequired,statusMessage:runtime.statusMessage,configured:runtime.configured,keyConfigured:!!config.OPENAI_API_KEY,modelConfigured:runtime.modelConfigured,model:runtime.model,maxCharsPerJob:config.MAX_SOURCE_CHARS_PER_JOB,maxCharsPerDay:config.MAX_SOURCE_CHARS_PER_DAY,liveVerified:!!(verified.success&&verified.data.provider===runtime.provider&&verified.data.model===runtime.identity&&verified.data.promptVersion===runtime.promptVersion),verifiedAt:verified.success?verified.data.verifiedAt:null,glossaryRuleCount:translationGlossaryInfo().ruleCount,glossarySources:translationGlossaryInfo().sources,reviewedPairCount:reviewedTranslationPairs().length};
}
export function usage(){
  const row=db().prepare(`SELECT
    COALESCE(SUM(CASE WHEN u.reservation_status<>'released' THEN u.source_chars ELSE 0 END),0) AS sourceChars,
    COALESCE(SUM(CASE WHEN json_extract(i.scope_json,'$.provider') IN ('argos','finetuned','hymt') AND u.reservation_status<>'released' THEN u.source_chars ELSE 0 END),0) AS localSourceChars,
    COUNT(DISTINCT CASE WHEN json_extract(i.scope_json,'$.provider') IN ('argos','finetuned','hymt') AND u.reservation_status<>'released' THEN u.job_id END) AS localJobs,
    COALESCE(SUM(CASE WHEN COALESCE(json_extract(i.scope_json,'$.provider'),'openai') NOT IN ('argos','finetuned','hymt') AND u.reservation_status<>'released' THEN u.source_chars ELSE 0 END),0) AS remoteSourceChars,
    COALESCE(SUM(CASE WHEN COALESCE(json_extract(i.scope_json,'$.provider'),'openai') NOT IN ('argos','finetuned','hymt') THEN u.input_tokens ELSE 0 END),0) AS inputTokens,
    COALESCE(SUM(CASE WHEN COALESCE(json_extract(i.scope_json,'$.provider'),'openai') NOT IN ('argos','finetuned','hymt') THEN u.output_tokens ELSE 0 END),0) AS outputTokens,
    COUNT(CASE WHEN COALESCE(json_extract(i.scope_json,'$.provider'),'openai') NOT IN ('argos','finetuned','hymt') AND (u.reservation_status='unknown' OR (u.reservation_status='reported' AND (u.input_tokens IS NULL OR u.output_tokens IS NULL))) THEN 1 END) AS unknownCount
    FROM usage_records u LEFT JOIN job_items i ON i.id=u.job_item_id`).get() as Row;
  return row;
}
export function baseBootstrap(){return {resources:resourceRows(),modules:moduleRows(),glossary:glossaryRows(),toolGuides,notes:noteRows(),bookmarks:bookmarkRows(),positions:positionRows(),progress:progressRows(),settings:getSettings(),translationStatus:translationStatus(),usage:usage()};}
export function resourceDetail(resourceId:string){const resources=resourceRows();const resource=resources.find(r=>r.id===resourceId);if(!resource)throw new AppError('NOT_FOUND','자료를 찾을 수 없습니다.',404);const relations=(db().prepare('SELECT * FROM resource_relations WHERE parent_id=? OR child_id=?').all(resourceId,resourceId) as Row[]).flatMap(rel=>{const other=resources.find(r=>r.id===(rel.parent_id===resourceId?rel.child_id:rel.parent_id));return other?[{...other,relation:rel.relation}]:[];});return {resource,versions:(db().prepare('SELECT * FROM source_versions WHERE resource_id=? ORDER BY imported_at DESC').all(resourceId) as Row[]).map(versionRow),relations,modules:moduleRows().filter(m=>m.resourceIds.includes(resourceId)),position:positionRows().find(p=>p.resourceId===resourceId)||null};}
